name: Deploy to S3
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build production code
        run: |
          cd ${{ github.workspace }}
          npm install
          npm run build
          ls build/
      - run: echo "🍏 This job's status is ${{ job.status }}."
